### ISSUE TITLE
Set document.body.appendChild(generatedElement)

### ISSUE THREAD

**Issue by englishextra** [Damian96/html-to-dom#1]
This will ease the copy/paste of the result JS.

Also, setting `<body>` element by hand in input field also makes the whole workflow uncomfortable.

Thanks

**Comment by Damian96** [comment]
Thank you for the suggestion, I will add an option `Container`,
as an input field that accepts a `tagName` and uses that as the container element.
I think it's better to leave it as a default option, so someone can always convert just a single element.

**Comment by englishextra** [comment]
Thanks
